@startuml
skinparam style strictuml
class Histoire4{ 

 } 
class Genre{ 

 } 
class HorsLaLoi{ 

 } 
class Cowboy{ 
- gains
- captures
- {static} boissonParDefaut

 } 
class Nommable{ 

 } 
class Ripou{ 
- brigand

 } 
class Dame{ 
- estLibre
- sauveur
- ravisseur
- {static} boissonParDefaut

 } 
class Substantif{ 
- nom
- genre

 } 
class Narrateur{ 

 } 
class Personnage{ 
- {static} BOISSON_PAR_DEFAUT
- nom
- boisson

 } 
class Brigand{ 
# {static} LOOK_PAR_DEFAUT
- look
- recompense
- estLibre
- captives
- gardien
- {static} boissonParDefaut

 } 
class Boisson{ 
- final substantif
+ {static} final EAU

 } 
@enduml
