@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class PumlDoclet
class dccDiagram
class Java2Puml
class dcaDiagram
'enum PumlType

Java2Puml " 1\t" --> "\t1" PumlDoclet : appelle à l'aide de javadoc >
PumlDoclet " 1\t" --> "\t1" dcaDiagram  : envoie une liste d'élement du package \n<<use>>
PumlDoclet " 1\t" --> "\t1" dccDiagram : envoie une liste d'éledu package > \n <<use>>


@enduml