@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class PumlDoclet
class PumlDiagram
class Java2Puml
class FirstDoclet

Java2Puml " 1\t" --> "\t1" PumlDoclet : appelle à l'aide de javadoc >
PumlDoclet " 1\t" --> "\t1" PumlDiagram : envoie une liste d'élement du package >


@enduml