@startuml
'https://plantuml.com/class-diagram 
 skinparam classAttributeIconSize 0 
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members
package pumlFromJava{
class dcaDiagram extends umlDiagram{ 

 } 
class PumlDoclet implements Doclet{ 

 } 
class FirstDoclet implements Doclet{ 

 } 
class Java2Puml{ 

 } 
abstract class umlDiagram{ 

 } 
class dccDiagram extends umlDiagram{ 

 } 
}
@enduml
