@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class Java2Puml
{
   +main(args : String[])
}
class PumlDoclet
{
+init(locale : Locale, reporter : Reporter)
+getName() : String
+getSupportedOptions() : Set<? extends Option>
+getSupportedSourceVersion() : SourceVersion
+run(environment : DocletEnvironment) : Boolean
+ dumpElement(element : Element)
}


Java2Puml " 1\t" --> "\t1" PumlDoclet : appelle à l'aide de javadoc >


@enduml