@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class Java2Puml
{
   +{static}main(String[]:args)
}
class FirstDoclet
{
+init(Locale:locale, Reporter:reporter)
+getName() : String
+getSupportedOptions() : Set<? extends Option>
+getSupportedSourceVersion() : SourceVersion
+run(DocletEnvironment:environment) : boolean
+ dumpElement(Element:element)
}

package Western{}

Java2Puml " 1\t" --> "\t1" FirstDoclet : appelle à l'aide de javadoc >
FirstDoclet " 1\t" -> "\t*" Western : récupère les données >


@enduml