@startuml
'https://plantuml.com/class-diagram
 skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class dcaDiagram{
<<Create>> dcaDiagram()
+ generatePuml(ArrayList<Element> classes,String : d,String : out) : String
# processInsideClass(Element : e) : String
}

class dccDiagram{
# String : uml
+ <<Create>> dccDiagram()
# generatePuml(ArrayList<Element> classes,String : d,String : out) : String
# processInsideClass(Element : e) : String
# handleModifiers(Element : e) : String
# processClass(Element : e) : String
 }



class PumlDoclet{
+ <<Create>> PumlDoclet()
+ init(Locale : locale,Reporter : reporter)
+ getName() : String
+ getSupportedOptions() : Set<? extends Option>
+ getSupportedSourceVersion() : SourceVersion
+ run(DocletEnvironment : environement) : boolean

 }

class Java2Puml{
+ <<Create>> Java2Puml()
+ main(String[])
 }

'enum PumlType <<enum>> {
'  DCA
'  DCC
'}

Java2Puml " 1\t" --> "\t1" PumlDoclet : appelle à l'aide de javadoc >
PumlDoclet " 1\t" --> "\t1" dcaDiagram  : envoie une liste d'élement du package \n<<use>>
PumlDoclet " 1\t" --> "\t1" dccDiagram : envoie une liste d'éledu package > \n <<use>>

@enduml

