@startuml
'https://plantuml.com/class-diagram 
 skinparam classAttributeIconSize 0 
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members
class FirstDoclet{ 
+ <<Create>> FirstDoclet()
+ init(java.util.Locale,jdk.javadoc.doclet.Reporter) : void
+ getName() : String 
+ getSupportedOptions() : java.util.Set<? extends jdk.javadoc.doclet.Doclet.Option>
+ getSupportedSourceVersion() : javax.lang.model.SourceVersion
+ run(jdk.javadoc.doclet.DocletEnvironment) : boolean
- dumpElement(javax.lang.model.element.Element) : void

 } 
enum PumlType <<enum>> { 
+ {static} values() : pumlFromJava.PumlType[]
+ {static} valueOf(java.lang.String) : pumlFromJava.PumlType
- <<Create>> PumlType()

 } 
class PumlDoclet{ 
+ <<Create>> PumlDoclet()
+ init(java.util.Locale,jdk.javadoc.doclet.Reporter) : void
+ getName() : String 
+ getSupportedOptions() : java.util.Set<? extends pumlFromJava.PumlDoclet.Option>
+ getSupportedSourceVersion() : javax.lang.model.SourceVersion
+ run(jdk.javadoc.doclet.DocletEnvironment) : boolean

 } 
class PumlDiagram{ 
+ <<Create>> PumlDiagram()
+ {static} generatePuml(java.util.ArrayList<javax.lang.model.element.Element>,java.lang.String,java.lang.String,pumlFromJava.PumlType) : void
- {static} processInsideClass(java.io.FileWriter,javax.lang.model.element.Element) : void
- {static} handleModifiers(java.io.FileWriter,javax.lang.model.element.Element) : void
- {static} processClass(java.io.FileWriter,javax.lang.model.element.Element) : void
+ toString() : String 

 } 
class Java2Puml{ 
+ <<Create>> Java2Puml()
+ {static} main(java.lang.String[]) : void

 } 
@enduml
