@startuml
'https://plantuml.com/class-diagram 
 skinparam classAttributeIconSize 0 
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members
class dcaDiagram{ 
ERROR<<Create>> dcaDiagram()
+ generatePuml(java.util.ArrayList<javax.lang.model.element.Element>,java.lang.String,java.lang.String) : String 
# processInsideClass(javax.lang.model.element.Element) : String 

 } 
class PumlDoclet{ 
+ <<Create>> PumlDoclet()
+ init(java.util.Locale,jdk.javadoc.doclet.Reporter)
+ getName() : String 
+ getSupportedOptions() : java.util.Set<? extends pumlFromJava.PumlDoclet.Option>
+ getSupportedSourceVersion() : javax.lang.model.SourceVersion
+ run(jdk.javadoc.doclet.DocletEnvironment) : boolean

 } 
class FirstDoclet{ 
+ <<Create>> FirstDoclet()
+ init(java.util.Locale,jdk.javadoc.doclet.Reporter)
+ getName() : String 
+ getSupportedOptions() : java.util.Set<? extends jdk.javadoc.doclet.Doclet.Option>
+ getSupportedSourceVersion() : javax.lang.model.SourceVersion
+ run(jdk.javadoc.doclet.DocletEnvironment) : boolean
- dumpElement(javax.lang.model.element.Element)

 } 
class Java2Puml{ 
+ <<Create>> Java2Puml()
+ main(java.lang.String[])

 } 
enum PumlType <<enum>> { 
+ values() : pumlFromJava.PumlType[]
+ valueOf(java.lang.String) : pumlFromJava.PumlType
- <<Create>> PumlType()

 } 
class dccDiagram{ 
+ <<Create>> dccDiagram()
# generatePuml(java.util.ArrayList<javax.lang.model.element.Element>,java.lang.String,java.lang.String) : String 
# processInsideClass(javax.lang.model.element.Element) : String 
# handleModifiers(javax.lang.model.element.Element) : String 
# processClass(javax.lang.model.element.Element) : String 

 } 
@enduml
