@startuml
'https://plantuml.com/class-diagram 
 skinparam classAttributeIconSize 0 
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members
package western{
class Histoire4{ 

 } 
enum Genre <<enum>> { 

 } 
interface HorsLaLoi implements Nommable{ 
<<interface>>
 } 
class Cowboy extends Personnage{ 
gains : int

 } 
interface Nommable{ 
<<interface>>
 } 
class Ripou extends Cowboy implements HorsLaLoi{ 

 } 
class Dame extends Personnage{ 
estLibre : boolean

 } 
class Substantif{ 

 } 
class Narrateur extends Personnage{ 

 } 
abstract class Personnage implements Nommable{ 

 } 
class Brigand extends Personnage implements HorsLaLoi{ 
recompense : int
estLibre : boolean

 } 
class Boisson{ 

 } 
Cowboy o--> HorsLaLoi
Cowboy o--> Boisson
Ripou o--> Brigand
Dame o--> Cowboy
Dame o--> HorsLaLoi
Dame o--> Boisson
Substantif o--> Genre
Personnage o--> Boisson
Personnage o--> Boisson
Brigand o--> Dame
Brigand o--> Cowboy
Brigand o--> Boisson
Boisson o--> Substantif
Boisson*->Boisson
}
@enduml
