@startuml
'https://plantuml.com/class-diagram 
 skinparam classAttributeIconSize 0 
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members
package western{ 
class Cowboy{ 
- gains : int

 } 
class Brigand{ 
- recompense : int
- estLibre : boolean

 } 
class Dame{ 
- estLibre : boolean

 } 
class Boisson{ 

 } 
class Histoire4{ 

 } 
class Narrateur{ 

 } 
class Ripou{ 

 } 
class Substantif{ 

 } 
enum Genre <<enum>> { 

 } 
interface Nommable <<interface>> { 

 } 
abstract class Personnage{ 

 } 
interface HorsLaLoi <<interface>> { 

 } 
}
@enduml
