@startuml
skinparam style strictuml
class western.Cowboy
class western.Brigand
class western.Dame
class western.Boisson
class western.Histoire4
class western.Narrateur
class western.Ripou
class western.Substantif
class western.Genre
class western.Nommable
class western.Personnage
class western.HorsLaLoi
@enduml
