@startuml
'https://plantuml.com/class-diagram 
 skinparam classAttributeIconSize 0 
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members
package western{
class Cowboy extends Personnage{ 
gains

 } 
class Brigand extends Personnage implements HorsLaLoi{ 
recompense
estLibre

 } 
class Dame extends Personnage{ 
estLibre

 } 
class Boisson{ 

 } 
class Histoire4{ 

 } 
class Narrateur extends Personnage{ 

 } 
class Ripou extends Cowboy implements HorsLaLoi{ 

 } 
class Substantif{ 

 } 
enum Genre <<enum>> { 

 } 
interface Nommable{ 
<<interface>>
 } 
abstract class Personnage implements Nommable{ 

 } 
interface HorsLaLoi implements Nommable{ 
<<interface>>
 } 
Cowboy-HorsLaLoi
Cowboy-Boisson
Brigand-Dame
Brigand-Cowboy
Brigand-Boisson
Dame-Cowboy
Dame-HorsLaLoi
Dame-Boisson
Boisson-Substantif
Boisson-Boisson
Ripou-Brigand
Substantif-Genre
Personnage-Boisson
Personnage-Boisson
}
@enduml
